# .github/workflows/lint.yml
name: Lint

on:
  push:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --only dev --no-interaction --no-root

      - name: Run Black (check only)
        run: poetry run black --check .

      - name: Run Ruff (non-blocking)
        run: |
          poetry run ruff check . || echo "::warning::Ruff found issues (see log above)"
